urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/new/', PostCreateView.as_view(), name='post_create'),
    path('posts/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('posts/<int:pk>/like/', add_like, name='add_like'),
    path('posts/<int:pk>/dislike/', remove_like, name='remove_like'),
    path('accounts/logout/', logout_view, name='logout'),
]

models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='liked_posts', through='Like')
    image = models.ImageField(upload_to="img", null=True, blank=True)

    def __str__(self):
        return self.title

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'post')

forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = "__all__"

views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.conf import settings
from .models import Post, Category, Like

class PostDetailView(DetailView):
    model = Post

class PostListView(ListView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['MEDIA_URL'] = settings.MEDIA_URL
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'text', 'category', 'image']
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'text', 'category']

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/posts/'

class CategoryDetailView(DetailView):
    model = Category

class CategoryListView(ListView):
    model = Category

def add_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    like = Like(user=request.user, post=post)
    like.save()
    return redirect('blog:post_detail', pk=pk)

def remove_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    like = Like.objects.get(user=request.user, post=post)
    like.delete()
    return redirect('blog:post_detail', pk=pk)

def logout_view(request):
    logout(request)
    return redirect('blog:post_list')

templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
    <div class="page-container">
    {% include "blog/menu.html" %}     
    {% block content%}{% endblock %}
    </div>
</body>
</html>

templates/blog/category_detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>Блог</h1>
<h2>{{ category.title }}</h2>
<ul>
    {% for post in category.post_set.all %}
        <li><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
{% if not category.post_set.all %}
    <p>No posts found</p>
{% endif %}
{% endblock %}

templates/blog/category_list.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>Блог</h1>
<h2>Все категории</h2>
  <ul>
    {% for category in object_list %}
      <li>{{ category.title }}
        <ul>
          {% for post in category.post_set.all %}
            <li><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/blog/login.html
{% extends "blog/base.html" %}
{% block title %}Авторзция{% endblock %}
{% block content %}
        <h1 class="page-title">Блог</h1>
        <section class="section-wrapper">
            <h2 class="section-title">Авторизация</h2>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Войти</button>
            </form>
        </section>
        <a class="add_post" href="{% url 'blog:add_post' %}">добавить запись</a>
{% endblock %}

templates/blog/menu.html
{% if user.is_authenticated %}
    <p>Пользователь <strong>{{ user.username }}</strong> авторизован, его ID {{ user.id }} <a href="{% url 'blog:logout' %}">выйти</a></p>
{% else %}
    <a href="{% url 'login' %}">войти</a>
    <a href="">зарегистрироваться</a>
{% endif %}

templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block title %}Удалить запись{% endblock %}
{% block content %}
        <h1 class="page-title">Блог</h1>
        <section class="section-wrapper">
            <h2 class="section-title">Удалить запись</h2>
            <form method="post">{% csrf_token %}
                <p>Вы хотите удалить запись {{ object.title }}?</p>
                {{ form }}
                <input type="submit" value="Удалить">
            </form>
        </section>
        <a class="add_post" href="{% url 'blog:index' %}">смотреть все записи</a>
{% endblock %}

templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

<h1>Блог</h1>
<h2>{{ object.title }}</h2>
<p>{{ object.text }}</p>
<p>опубликовано {{ post.date }} {{ post.time }} пользователем {{ post.author }}, его ID {{ post.author.id }}</p>
<p>категория
    <a href="{% url 'blog:category_detail' post.category.pk %}">
        {{ object.category.title }}
    </a>
</p>
<p>количество лайков {{ object.likes.count }}
{% if object.likes.count %}
<p>понравилось пользователям:
    <ul>
    {% for like in post.like_set.all %}
        <li>{{ like.user.username }}</li>
    {% endfor %}
    </ul>
</p>
{% endif %}

<p>
    {% if request.user in object.likes.all %}
        <a href="{% url 'blog:remove_like' object.pk %}">не нравится</a>
    {% else %}
        <a href="{% url 'blog:add_like' object.pk %}">нравится</a>
    {% endif %}
</p>

<p>
{% if user.is_authenticated %}
    {% if post.author.id == user.id %}
        <a href="">редактировать запись</a><br>
        <a href="">удалить запись</a>
    {% endif %}
{% endif %}
</p>
<p>
    <a href="{%  url 'blog:post_list' %}">смотреть все записи</a>
</p>
{% endblock %}

templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block title %}Добавить запись{% endblock %}
{% block content %}
        <h1 class="page-title">Блог</h1>
        <section class="section-wrapper">
            <h2 class="section-title">Добавить запись в блог</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Добавить запись</button>
              </form>
        </section>
        <a class="add_post" href="{% url 'blog:post_list' %}">смотреть все записи</a>
{% endblock %}

templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block title %}Главная страница{% endblock %}
{% block content %}

<h1>Блог</h1>
<h2>Все записи</h2>
<div class="post-container">
    {% for post in object_list %}
        <article class="post-item">
            <img src="{{ MEDIA_URL }}{{ post.image }}" alt="фото записи">
            <a href="{% url 'blog:post_detail' post.pk %}">
                {{ post.title }}
            </a>
        </article>
    {% empty %}
        <span>Записей пока нет</span>
    {% endfor %}
</div>
<a href="{% url 'blog:post_create' %}">добавить запись</a>
{% endblock %}

templates/blog/post_update_form.html
{% extends "blog/base.html" %}
{% block title %}Редактировать запись{% endblock %}
{% block content %}
        <h1 class="page-title">Блог</h1>
        <section class="section-wrapper">
            <h2 class="section-title">Редактировать запись</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Сохранить изменения</button>
            </form>
        </section>
        <a class="add_post" href="{% url 'blog:index' %}">смотреть все записи</a>
{% endblock %}